module.exports = {
  icon: false,
  typescript: true,
  expandProps: 'end',
  prettier: true,
  svgo: false,
  replaceAttrValues: {
    '#844A09': '#ffff',
    '#995C0D': '#ffff',
    '#B27214': '#ffff',
    '#FCD495': '#ffff',
    '#FCD495': '#ffff',
    '#E2B376': '#ffff',
    '#2197D8': '#ffff',
    '#9AD14B': '#ffff',
    '#80A52F': '#ffff',
    '#4D4D4D': '#ffff',
    '#808080': '#ffff',
    '#666666': '#ffff',
  },
  outDir: './src/svg-components',
  index: false,
  ignoreExisting: false,
  filenameCase: 'pascal',
  ext: 'tsx',
  template: require('./svg-template.cjs'),
  indexTemplate: require('./index.template.cjs'),
};
// Configuration documentation: https://react-svgr.com/docs/options/
